//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailoBillSoftWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReturnDet
    {
        public int PR_detail_id { get; set; }
        public Nullable<int> Purchase_Return_Id { get; set; }
        public Nullable<int> Pur_Detail_Id { get; set; }
        public Nullable<int> SrNo { get; set; }
        public Nullable<int> Item_id { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> Barcode_Id { get; set; }
        public Nullable<decimal> Item_rate { get; set; }
        public Nullable<decimal> Discount_rate { get; set; }
        public Nullable<decimal> Discount_amount { get; set; }
        public Nullable<decimal> Ad_Rate { get; set; }
        public Nullable<decimal> Basic_Amt { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> Total_amount { get; set; }
        public Nullable<decimal> CGSTPer { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTPer { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> IGSTPer { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> VatPer { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual MstArticle MstArticle { get; set; }
        public virtual MstBrand MstBrand { get; set; }
        public virtual MstColour MstColour { get; set; }
        public virtual MstInventoryItem MstInventoryItem { get; set; }
        public virtual MstSize MstSize { get; set; }
        public virtual PurchaseReturnHD PurchaseReturnHD { get; set; }
        public virtual Barcode Barcode { get; set; }
    }
}
