//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailoBillSoftWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderHD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderHD()
        {
            this.PurchaseOrderDets = new HashSet<PurchaseOrderDet>();
            this.PurchaseHeads = new HashSet<PurchaseHead>();
        }
    
        public long Purchase_Order_ID { get; set; }
        public string Purchase_Order_Date { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<decimal> Net_Total_amount { get; set; }
        public Nullable<decimal> Total_item_quantity { get; set; }
        public Nullable<decimal> Total_item_Count { get; set; }
        public Nullable<decimal> Purchase_Order_No { get; set; }
        public string Quotation_Date { get; set; }
        public Nullable<int> Quotation_Ref_No { get; set; }
        public string VendorName { get; set; }
        public string VendorCode { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string VATGSTTIN { get; set; }
        public string PO_ValidTill { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ModRemarks { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> VatPer { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public Nullable<decimal> CGSTPer { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTPer { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> IGSTPer { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> GrossAmt { get; set; }
        public Nullable<decimal> RoundOff_Amt { get; set; }
        public string AmountinWords { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<decimal> OtherCharges1 { get; set; }
        public Nullable<decimal> OtherCharges2 { get; set; }
        public Nullable<decimal> OtherCharges3 { get; set; }
        public Nullable<decimal> DisPer { get; set; }
        public Nullable<decimal> DisAmt { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> FinYearID { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string DeliveryType { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public string Other4 { get; set; }
        public string Other5 { get; set; }
        public string PurchaseType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDet> PurchaseOrderDets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseHead> PurchaseHeads { get; set; }
    }
}
