//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailoBillSoftWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurDetail
    {
        public long PurDtId { get; set; }
        public Nullable<long> PurHdId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public string ArticleName { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> ColorId { get; set; }
        public string ColorName { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> SizeId { get; set; }
        public string SizeName { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> PurRate { get; set; }
        public Nullable<decimal> SaleRate { get; set; }
        public Nullable<decimal> PM { get; set; }
        public Nullable<decimal> DisPer { get; set; }
        public Nullable<decimal> DisAmt { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> VATPer { get; set; }
        public Nullable<decimal> VATAmt { get; set; }
        public Nullable<decimal> STPer { get; set; }
        public Nullable<decimal> STAmt { get; set; }
        public Nullable<decimal> CSTPer { get; set; }
        public Nullable<decimal> CSTAmt { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PODtId { get; set; }
        public string Tax { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<decimal> BalQty { get; set; }
    }
}
