//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailoBillSoftWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurHead
    {
        public long PurHdId { get; set; }
        public Nullable<long> PurNo { get; set; }
        public Nullable<System.DateTime> PurDate { get; set; }
        public string PurType { get; set; }
        public Nullable<long> AccId { get; set; }
        public string AccName { get; set; }
        public string AccCode { get; set; }
        public string RefBillNo { get; set; }
        public string ChallanNo { get; set; }
        public string ChallanRemarks { get; set; }
        public Nullable<decimal> PurAmount { get; set; }
        public Nullable<decimal> STAmt { get; set; }
        public Nullable<decimal> VATAmt { get; set; }
        public Nullable<decimal> CSTAmt { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<decimal> AfterDisAmt { get; set; }
        public Nullable<decimal> OtherCharges2 { get; set; }
        public Nullable<decimal> OtherCharges3 { get; set; }
        public Nullable<decimal> DisPer { get; set; }
        public Nullable<decimal> DisAmt { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<decimal> TotalCashDis { get; set; }
        public Nullable<decimal> TotalAdjustment { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> FinyearId { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string PurchaseRemarks { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryRemarks { get; set; }
        public string RefPoNo { get; set; }
        public Nullable<System.DateTime> RefPoDate { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<int> TotalItemQty { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Narration { get; set; }
        public string GrNo { get; set; }
        public string ModRemarks { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public string Other4 { get; set; }
        public string Other5 { get; set; }
        public string Other6 { get; set; }
        public string Other7 { get; set; }
        public string Other8 { get; set; }
        public string Other9 { get; set; }
        public string Other10 { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<long> BranchId { get; set; }
    }
}
