//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailoBillSoftWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationDet
    {
        public int QuotationDet_Id { get; set; }
        public Nullable<int> QuotationHD_ID { get; set; }
        public Nullable<int> SrNo { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> ItemQty { get; set; }
        public Nullable<decimal> ItemRate { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> VatPer { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public Nullable<decimal> CGSTPer { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTPer { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> IGSTPer { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public string HSNCode { get; set; }
        public string IsValBased { get; set; }
        public string Barcode { get; set; }
        public Nullable<decimal> PurRate { get; set; }
        public Nullable<decimal> SaleRate { get; set; }
        public Nullable<decimal> DisPer { get; set; }
        public Nullable<decimal> DisAmt { get; set; }
        public Nullable<int> RecQty { get; set; }
        public Nullable<int> LQty { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<decimal> BasicAmt { get; set; }
        public Nullable<decimal> AdRate { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
    
        public virtual MstArticle MstArticle { get; set; }
        public virtual MstBrand MstBrand { get; set; }
        public virtual MstColour MstColour { get; set; }
        public virtual MstInventoryItem MstInventoryItem { get; set; }
        public virtual MstSize MstSize { get; set; }
        public virtual QuotationHD QuotationHD { get; set; }
    }
}
